# Generated by Django 4.2.7 on 2025-09-06 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(default='A', max_length=5)),
                ('semester', models.IntegerField(default=1)),
                ('strength', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Group',
                'verbose_name_plural': 'Class Groups',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('school', 'School Level'), ('college', 'College Level'), ('university', 'University Level')], default='college', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('slot_duration', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('lunch_break_start', models.TimeField(default='13:00:00')),
                ('lunch_break_end', models.TimeField(default='14:00:00')),
                ('working_days', models.JSONField(default=list, help_text='List of working days (0=Monday, 6=Sunday)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('seminar_hall', 'Seminar Hall'), ('auditorium', 'Auditorium'), ('library', 'Library')], default='classroom', max_length=20)),
                ('capacity', models.IntegerField(default=60)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computer', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('building', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('availability', models.JSONField(default=dict, help_text='Day-wise availability slots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('lab', 'Laboratory'), ('skill', 'Skill Development'), ('project', 'Project Work')], default='core', max_length=20)),
                ('credits', models.IntegerField(default=3)),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=1)),
                ('theory_hours', models.IntegerField(default=3, help_text='Theory hours per week')),
                ('practical_hours', models.IntegerField(default=0, help_text='Practical hours per week')),
                ('tutorial_hours', models.IntegerField(default=0, help_text='Tutorial hours per week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('visiting_faculty', 'Visiting Faculty')], default='assistant_professor', max_length=30)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('max_hours_per_day', models.IntegerField(default=6)),
                ('max_hours_per_week', models.IntegerField(default=24)),
                ('max_consecutive_hours', models.IntegerField(default=3)),
                ('availability', models.JSONField(default=dict, help_text='Day-wise availability slots')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_level', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('can_teach_theory', models.BooleanField(default=True)),
                ('can_teach_practical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('generation_time', models.DurationField(blank=True, null=True)),
                ('algorithm_used', models.CharField(default='OR-Tools CP-SAT', max_length=50)),
                ('generation_parameters', models.JSONField(default=dict, help_text='Parameters used during generation')),
                ('total_sessions', models.IntegerField(default=0)),
                ('conflicts_resolved', models.IntegerField(default=0)),
                ('optimization_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
            },
        ),
        migrations.CreateModel(
            name='TimetableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('theory', 'Theory Class'), ('practical', 'Practical/Lab'), ('tutorial', 'Tutorial'), ('break', 'Break'), ('lunch', 'Lunch Break')], default='theory', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_fixed', models.BooleanField(default=False, help_text='Cannot be moved during editing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classgroup')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.room')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='timetable.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Session',
                'verbose_name_plural': 'Timetable Sessions',
            },
        ),
        migrations.CreateModel(
            name='TimetableConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('teacher_availability', 'Teacher Availability'), ('room_availability', 'Room Availability'), ('no_consecutive_subjects', 'No Consecutive Same Subject'), ('lunch_break', 'Lunch Break'), ('max_hours_per_day', 'Maximum Hours Per Day'), ('preferred_time_slots', 'Preferred Time Slots')], max_length=30)),
                ('parameters', models.JSONField(default=dict, help_text='Constraint-specific parameters')),
                ('priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='timetable.institution')),
            ],
            options={
                'verbose_name': 'Timetable Constraint',
                'verbose_name_plural': 'Timetable Constraints',
            },
        ),
    ]
